from __future__ import annotations

from .models import AccessClass, ConnectorManifest, ConnectorState


def _source(
    source_id: str,
    display_name: str,
    owner: str,
    access: AccessClass,
    state: ConnectorState,
    base_url: str | None,
    docs: str | None,
    **kwargs: object,
) -> ConnectorManifest:
    return ConnectorManifest(
        source_id=source_id,
        display_name=display_name,
        owner=owner,
        jurisdiction=None,
        access_class=access,
        state=state,
        base_url=base_url,
        documentation_url=docs,
        last_verified="2026-09-15",
        **kwargs,  # type: ignore[arg-type]
    )


SOURCES = {
    "crossref": _source(
        "crossref",
        "Crossref",
        "Crossref",
        AccessClass.PUBLIC_API,
        ConnectorState.ENABLED,
        "https://api.crossref.org",
        "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
        formats=("json",),
        item_license_required=True,
    ),
    "openalex": _source(
        "openalex",
        "OpenAlex",
        "OurResearch",
        AccessClass.PUBLIC_API,
        ConnectorState.ENABLED,
        "https://api.openalex.org",
        "https://docs.openalex.org/",
        formats=("json",),
        item_license_required=True,
    ),
    "datacite": _source(
        "datacite",
        "DataCite",
        "DataCite",
        AccessClass.PUBLIC_API,
        ConnectorState.ENABLED,
        "https://api.datacite.org",
        "https://support.datacite.org/docs/api",
        formats=("json",),
        item_license_required=True,
    ),
    "europe_pmc": _source(
        "europe_pmc",
        "Europe PMC",
        "EMBL-EBI",
        AccessClass.PUBLIC_API,
        ConnectorState.ENABLED,
        "https://www.ebi.ac.uk/europepmc/webservices/rest",
        "https://europepmc.org/RestfulWebService",
        formats=("json", "xml"),
        full_text=True,
    ),
    "arxiv": _source(
        "arxiv",
        "arXiv",
        "Cornell University",
        AccessClass.PUBLIC_API,
        ConnectorState.ENABLED,
        "https://export.arxiv.org",
        "https://info.arxiv.org/help/api/",
        formats=("atom",),
        full_text=True,
        rate_limit_per_second=0.33,
    ),
    "epo_ops": _source(
        "epo_ops",
        "EPO Open Patent Services",
        "European Patent Office",
        AccessClass.AUTH_REQUIRED,
        ConnectorState.DISABLED,
        "https://ops.epo.org",
        "https://developers.epo.org/",
        authentication="oauth2",
        credential_secret="EPO_OPS_CREDENTIALS",  # noqa: S106 - vault key name, not a secret
        reason="EPO OPS credentials are not configured",
    ),
    "wipo_patentscope": _source(
        "wipo_patentscope",
        "WIPO PATENTSCOPE",
        "WIPO",
        AccessClass.LICENSE_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://patentscope.wipo.int/",
        reason="A documented WIPO machine-access agreement is required",
    ),
    "lens": _source(
        "lens",
        "The Lens",
        "Cambia",
        AccessClass.LICENSE_REQUIRED,
        ConnectorState.DISABLED,
        "https://api.lens.org",
        "https://docs.api.lens.org/",
        authentication="bearer",
        credential_secret="LENS_API_TOKEN",  # noqa: S106 - vault key name, not a secret
        reason="Lens API licence and token are not configured",
    ),
    "aripo": _source(
        "aripo",
        "ARIPO",
        "African Regional Intellectual Property Organization",
        AccessClass.PARTNERSHIP_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://www.aripo.org/",
        reason="Documented machine access or a data-sharing partnership is required",
    ),
    "oapi": _source(
        "oapi",
        "OAPI",
        "Organisation Africaine de la Propriete Intellectuelle",
        AccessClass.PARTNERSHIP_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://oapi.int/",
        reason="Documented machine access or a data-sharing partnership is required",
    ),
    "cipc": _source(
        "cipc",
        "CIPC",
        "Companies and Intellectual Property Commission",
        AccessClass.PARTNERSHIP_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://www.cipc.co.za/",
        reason="Documented machine access or a data-sharing partnership is required",
    ),
    "ajol": _source(
        "ajol",
        "African Journals Online",
        "AJOL",
        AccessClass.PARTNERSHIP_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://www.ajol.info/",
        reason="An official feed, API, OAI-PMH endpoint or partnership is required",
    ),
    "africarxiv": _source(
        "africarxiv",
        "AfricArXiv",
        "AfricArXiv",
        AccessClass.PARTNERSHIP_REQUIRED,
        ConnectorState.DISABLED,
        None,
        "https://info.africarxiv.org/",
        reason="Repository endpoints must be mapped and verified before activation",
    ),
}

# Declared separately from executable adapters so absence of implementation can
# never fall through to ad-hoc HTML scraping.
for source_id, name, owner, docs in (
    ("unpaywall", "Unpaywall", "OurResearch", "https://unpaywall.org/products/api"),
    ("core", "CORE", "The Open University", "https://core.ac.uk/services/api"),
    ("openaire", "OpenAIRE", "OpenAIRE", "https://graph.openaire.eu/develop/api.html"),
    ("doaj", "DOAJ", "DOAJ", "https://doaj.org/api/"),
    ("orcid", "ORCID", "ORCID", "https://info.orcid.org/documentation/api-tutorials/"),
    ("ror", "ROR", "Research Organization Registry", "https://ror.readme.io/"),
    ("zenodo", "Zenodo", "CERN", "https://developers.zenodo.org/"),
    ("biorxiv", "bioRxiv", "Cold Spring Harbor Laboratory", "https://api.biorxiv.org/"),
    ("medrxiv", "medRxiv", "Cold Spring Harbor Laboratory", "https://api.biorxiv.org/"),
    ("osf_preprints", "OSF Preprints", "Center for Open Science", "https://developer.osf.io/"),
):
    SOURCES[source_id] = _source(
        source_id,
        name,
        owner,
        AccessClass.PUBLIC_API,
        ConnectorState.DISABLED,
        None,
        docs,
        reason="Documented adapter is declared but not yet implemented and verified",
    )

for source_id, name, owner, access, docs, reason in (
    (
        "chemrxiv",
        "ChemRxiv",
        "American Chemical Society",
        AccessClass.METADATA_ONLY,
        "https://chemrxiv.org/",
        "Documented machine endpoint and item licences require verification",
    ),
    (
        "uspto",
        "USPTO Open Data",
        "United States Patent and Trademark Office",
        AccessClass.PUBLIC_API,
        "https://developer.uspto.gov/",
        "Official API product and schema require configuration and contract tests",
    ),
    (
        "google_patents",
        "Google Patents",
        "Google",
        AccessClass.METADATA_ONLY,
        "https://patents.google.com/",
        "No general HTML scraper is authorised; configure a documented dataset route",
    ),
):
    SOURCES[source_id] = _source(
        source_id,
        name,
        owner,
        access,
        ConnectorState.DISABLED,
        None,
        docs,
        reason=reason,
    )
